-- MySQL Script generated by MySQL Workbench
-- 11/29/18 15:46:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema compromarc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `compromarc` ;

-- -----------------------------------------------------
-- Schema compromarc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compromarc` DEFAULT CHARACTER SET latin1 ;
USE `compromarc` ;

-- -----------------------------------------------------
-- Table `compromarc`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compromarc`.`usuario` ;

CREATE TABLE IF NOT EXISTS `compromarc`.`usuario` (
  `idusuario` INT(11) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `cedula` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `compromarc`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compromarc`.`cliente` ;

CREATE TABLE IF NOT EXISTS `compromarc`.`cliente` (
  `idcliente` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `compromarc`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compromarc`.`producto` ;

CREATE TABLE IF NOT EXISTS `compromarc`.`producto` (
  `idproducto` INT(11) NOT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `tipo_producto` VARCHAR(41) NULL DEFAULT NULL,
  `calidad_producto` VARCHAR(30) NULL DEFAULT NULL,
  `precio_producto` INT(11) NULL DEFAULT NULL,
  `descripcion_producto` VARCHAR(300) NULL DEFAULT NULL,
  `idusuario` VARCHAR(45) NOT NULL,
  `idcliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproducto`, `idusuario`, `idcliente`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `compromarc`.`cliente_has_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compromarc`.`cliente_has_producto` ;

CREATE TABLE IF NOT EXISTS `compromarc`.`cliente_has_producto` (
  `cliente_idcliente` INT(11) NOT NULL,
  `producto_idproducto` INT(11) NOT NULL,
  `producto_idusuario` VARCHAR(45) NOT NULL,
  `producto_idcliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cliente_idcliente`, `producto_idproducto`, `producto_idusuario`, `producto_idcliente`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `compromarc`.`usuario_has_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compromarc`.`usuario_has_producto` ;

CREATE TABLE IF NOT EXISTS `compromarc`.`usuario_has_producto` (
  `usuario_idusuario` INT(11) NOT NULL,
  `producto_idproducto` INT(11) NOT NULL,
  `producto_idusuario` VARCHAR(45) NOT NULL,
  `producto_idcliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `producto_idproducto`, `producto_idusuario`, `producto_idcliente`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
